plugins {
    id 'java'
}

group = 'com.dipesh.mainali'
version = '0.0.1-SNAPSHOT'
description = 'LeetCode'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}